// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/feed/feed.proto

package feed_service // import "rpc/feed/pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReFreshRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReFreshRequest) Reset()         { *m = ReFreshRequest{} }
func (m *ReFreshRequest) String() string { return proto.CompactTextString(m) }
func (*ReFreshRequest) ProtoMessage()    {}
func (*ReFreshRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_feed_183ba5cda355943a, []int{0}
}
func (m *ReFreshRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReFreshRequest.Unmarshal(m, b)
}
func (m *ReFreshRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReFreshRequest.Marshal(b, m, deterministic)
}
func (dst *ReFreshRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReFreshRequest.Merge(dst, src)
}
func (m *ReFreshRequest) XXX_Size() int {
	return xxx_messageInfo_ReFreshRequest.Size(m)
}
func (m *ReFreshRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReFreshRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReFreshRequest proto.InternalMessageInfo

func (m *ReFreshRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type GetFeedRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Cursor               int64    `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
	Offset               int64    `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFeedRequest) Reset()         { *m = GetFeedRequest{} }
func (m *GetFeedRequest) String() string { return proto.CompactTextString(m) }
func (*GetFeedRequest) ProtoMessage()    {}
func (*GetFeedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_feed_183ba5cda355943a, []int{1}
}
func (m *GetFeedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeedRequest.Unmarshal(m, b)
}
func (m *GetFeedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeedRequest.Marshal(b, m, deterministic)
}
func (dst *GetFeedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedRequest.Merge(dst, src)
}
func (m *GetFeedRequest) XXX_Size() int {
	return xxx_messageInfo_GetFeedRequest.Size(m)
}
func (m *GetFeedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedRequest proto.InternalMessageInfo

func (m *GetFeedRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GetFeedRequest) GetCursor() int64 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

func (m *GetFeedRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetFeedResponse struct {
	ArticleIds           []int64  `protobuf:"varint,1,rep,packed,name=article_ids,json=articleIds" json:"article_ids,omitempty"`
	NextCursor           int64    `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor" json:"next_cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFeedResponse) Reset()         { *m = GetFeedResponse{} }
func (m *GetFeedResponse) String() string { return proto.CompactTextString(m) }
func (*GetFeedResponse) ProtoMessage()    {}
func (*GetFeedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_feed_183ba5cda355943a, []int{2}
}
func (m *GetFeedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeedResponse.Unmarshal(m, b)
}
func (m *GetFeedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeedResponse.Marshal(b, m, deterministic)
}
func (dst *GetFeedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedResponse.Merge(dst, src)
}
func (m *GetFeedResponse) XXX_Size() int {
	return xxx_messageInfo_GetFeedResponse.Size(m)
}
func (m *GetFeedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedResponse proto.InternalMessageInfo

func (m *GetFeedResponse) GetArticleIds() []int64 {
	if m != nil {
		return m.ArticleIds
	}
	return nil
}

func (m *GetFeedResponse) GetNextCursor() int64 {
	if m != nil {
		return m.NextCursor
	}
	return 0
}

type PushSelfFeedRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	ArticleId            int64    `protobuf:"varint,2,opt,name=article_id,json=articleId" json:"article_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushSelfFeedRequest) Reset()         { *m = PushSelfFeedRequest{} }
func (m *PushSelfFeedRequest) String() string { return proto.CompactTextString(m) }
func (*PushSelfFeedRequest) ProtoMessage()    {}
func (*PushSelfFeedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_feed_183ba5cda355943a, []int{3}
}
func (m *PushSelfFeedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushSelfFeedRequest.Unmarshal(m, b)
}
func (m *PushSelfFeedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushSelfFeedRequest.Marshal(b, m, deterministic)
}
func (dst *PushSelfFeedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushSelfFeedRequest.Merge(dst, src)
}
func (m *PushSelfFeedRequest) XXX_Size() int {
	return xxx_messageInfo_PushSelfFeedRequest.Size(m)
}
func (m *PushSelfFeedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushSelfFeedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushSelfFeedRequest proto.InternalMessageInfo

func (m *PushSelfFeedRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PushSelfFeedRequest) GetArticleId() int64 {
	if m != nil {
		return m.ArticleId
	}
	return 0
}

type PushFollowFeedRequest struct {
	Uids                 []int64  `protobuf:"varint,1,rep,packed,name=uids" json:"uids,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	ArticleId            int64    `protobuf:"varint,3,opt,name=article_id,json=articleId" json:"article_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushFollowFeedRequest) Reset()         { *m = PushFollowFeedRequest{} }
func (m *PushFollowFeedRequest) String() string { return proto.CompactTextString(m) }
func (*PushFollowFeedRequest) ProtoMessage()    {}
func (*PushFollowFeedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_feed_183ba5cda355943a, []int{4}
}
func (m *PushFollowFeedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushFollowFeedRequest.Unmarshal(m, b)
}
func (m *PushFollowFeedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushFollowFeedRequest.Marshal(b, m, deterministic)
}
func (dst *PushFollowFeedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushFollowFeedRequest.Merge(dst, src)
}
func (m *PushFollowFeedRequest) XXX_Size() int {
	return xxx_messageInfo_PushFollowFeedRequest.Size(m)
}
func (m *PushFollowFeedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushFollowFeedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushFollowFeedRequest proto.InternalMessageInfo

func (m *PushFollowFeedRequest) GetUids() []int64 {
	if m != nil {
		return m.Uids
	}
	return nil
}

func (m *PushFollowFeedRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PushFollowFeedRequest) GetArticleId() int64 {
	if m != nil {
		return m.ArticleId
	}
	return 0
}

type ActionFeedRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	ToUid                int64    `protobuf:"varint,2,opt,name=to_uid,json=toUid" json:"to_uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionFeedRequest) Reset()         { *m = ActionFeedRequest{} }
func (m *ActionFeedRequest) String() string { return proto.CompactTextString(m) }
func (*ActionFeedRequest) ProtoMessage()    {}
func (*ActionFeedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_feed_183ba5cda355943a, []int{5}
}
func (m *ActionFeedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionFeedRequest.Unmarshal(m, b)
}
func (m *ActionFeedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionFeedRequest.Marshal(b, m, deterministic)
}
func (dst *ActionFeedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionFeedRequest.Merge(dst, src)
}
func (m *ActionFeedRequest) XXX_Size() int {
	return xxx_messageInfo_ActionFeedRequest.Size(m)
}
func (m *ActionFeedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionFeedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActionFeedRequest proto.InternalMessageInfo

func (m *ActionFeedRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ActionFeedRequest) GetToUid() int64 {
	if m != nil {
		return m.ToUid
	}
	return 0
}

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_feed_183ba5cda355943a, []int{6}
}
func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (dst *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(dst, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ReFreshRequest)(nil), "feed.ReFreshRequest")
	proto.RegisterType((*GetFeedRequest)(nil), "feed.GetFeedRequest")
	proto.RegisterType((*GetFeedResponse)(nil), "feed.GetFeedResponse")
	proto.RegisterType((*PushSelfFeedRequest)(nil), "feed.PushSelfFeedRequest")
	proto.RegisterType((*PushFollowFeedRequest)(nil), "feed.PushFollowFeedRequest")
	proto.RegisterType((*ActionFeedRequest)(nil), "feed.ActionFeedRequest")
	proto.RegisterType((*EmptyResponse)(nil), "feed.EmptyResponse")
}

func init() { proto.RegisterFile("proto/feed/feed.proto", fileDescriptor_feed_183ba5cda355943a) }

var fileDescriptor_feed_183ba5cda355943a = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x4f, 0x6f, 0xda, 0x40,
	0x10, 0xc5, 0x65, 0x4c, 0xa9, 0x3a, 0x14, 0x28, 0x4b, 0xdd, 0xba, 0x54, 0x55, 0x91, 0x4f, 0x9c,
	0xa8, 0xd4, 0xf6, 0xd4, 0xa2, 0x56, 0xf4, 0x8f, 0x51, 0x6e, 0x91, 0x11, 0x97, 0x28, 0x92, 0x15,
	0xec, 0xb1, 0xb0, 0xe4, 0x78, 0x9d, 0xdd, 0x35, 0x49, 0xbe, 0x60, 0x3e, 0x57, 0xb4, 0x6b, 0x1b,
	0x63, 0x30, 0x48, 0x51, 0x2e, 0xb0, 0xf3, 0x34, 0xfb, 0x7b, 0xe3, 0x79, 0x5a, 0x30, 0x12, 0x46,
	0x05, 0xfd, 0x12, 0x20, 0xfa, 0xea, 0x67, 0xa2, 0x6a, 0xd2, 0x94, 0x67, 0xcb, 0x82, 0xae, 0x83,
	0x36, 0x43, 0xbe, 0x76, 0xf0, 0x26, 0x45, 0x2e, 0xc8, 0x1b, 0xd0, 0xd3, 0xd0, 0x37, 0xb5, 0x91,
	0x36, 0xd6, 0x1d, 0x79, 0xb4, 0x1c, 0xe8, 0xce, 0x51, 0xd8, 0x88, 0xfe, 0xd1, 0x1e, 0xf2, 0x0e,
	0x5a, 0x5e, 0xca, 0x38, 0x65, 0x66, 0x43, 0x89, 0x79, 0x25, 0x75, 0x1a, 0x04, 0x1c, 0x85, 0xa9,
	0x67, 0x7a, 0x56, 0x59, 0x0b, 0xe8, 0x6d, 0x99, 0x3c, 0xa1, 0x31, 0x47, 0xf2, 0x19, 0xda, 0x57,
	0x4c, 0x84, 0x5e, 0x84, 0x6e, 0xe8, 0x73, 0x53, 0x1b, 0xe9, 0x63, 0xdd, 0x81, 0x5c, 0x3a, 0xf3,
	0xb9, 0x6c, 0x88, 0xf1, 0x4e, 0xb8, 0x15, 0x23, 0x90, 0xd2, 0x5f, 0xa5, 0x58, 0x36, 0x0c, 0xce,
	0x53, 0xbe, 0x5e, 0x60, 0x14, 0x9c, 0x9e, 0xf6, 0x13, 0x40, 0x69, 0x95, 0x83, 0x5e, 0x6d, 0x9d,
	0xac, 0x4b, 0x30, 0x24, 0xc7, 0xa6, 0x51, 0x44, 0x6f, 0x77, 0x49, 0x04, 0x9a, 0x69, 0x39, 0x9b,
	0x3a, 0x17, 0xf4, 0xc6, 0x31, 0xba, 0xbe, 0x4f, 0x9f, 0x42, 0x7f, 0xe6, 0x89, 0x90, 0xc6, 0xa7,
	0x67, 0x34, 0xa0, 0x25, 0xa8, 0x5b, 0xa2, 0x5f, 0x08, 0xba, 0x0c, 0x7d, 0xab, 0x07, 0x9d, 0xff,
	0xd7, 0x89, 0xb8, 0x2f, 0xd6, 0xf6, 0xf5, 0x41, 0x07, 0x90, 0xa4, 0x05, 0xb2, 0x0d, 0x32, 0xf2,
	0x1d, 0x5e, 0x3a, 0x18, 0xc8, 0x40, 0xc9, 0xdb, 0x89, 0x8a, 0xbb, 0x9a, 0xef, 0x70, 0x90, 0xa9,
	0x15, 0x08, 0xf9, 0x01, 0xed, 0x39, 0x8a, 0x62, 0x71, 0xc5, 0xcd, 0x6a, 0xea, 0x43, 0x63, 0x4f,
	0xcd, 0xef, 0xfe, 0x82, 0xd7, 0xbb, 0x5b, 0x27, 0x1f, 0xb2, 0xb6, 0x9a, 0x24, 0xea, 0xbd, 0xa7,
	0xd0, 0x91, 0xc8, 0xed, 0xb2, 0x9f, 0xe6, 0xfe, 0x0f, 0xba, 0xd5, 0xac, 0xc8, 0xc7, 0xd2, 0xff,
	0x20, 0xc1, 0xda, 0x09, 0xc6, 0x1a, 0xf9, 0x0d, 0xbd, 0xac, 0x77, 0x16, 0x08, 0x64, 0x0a, 0xf3,
	0x3e, 0xeb, 0x3c, 0x88, 0xaa, 0xfe, 0x23, 0x66, 0xd0, 0x5f, 0xc6, 0xc1, 0x73, 0x10, 0x7f, 0x86,
	0x17, 0x26, 0x4b, 0xbc, 0xec, 0x9d, 0x26, 0xab, 0x9f, 0xf2, 0xdf, 0xe5, 0xc8, 0x36, 0xa1, 0x87,
	0xab, 0x96, 0x7a, 0xb3, 0xdf, 0x1e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x71, 0x92, 0xee, 0xb0, 0xcc,
	0x03, 0x00, 0x00,
}
